# https://coderabbit.ai/docs/get-started/customize-coderabbit

language: "ja"
early_access: true
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/.xml"
  path_instructions:
    - path: "**.ts"
      instructions: "Review the TypeScript code for conformity with the Google TypeScript style guide, highlighting any deviations."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - ":construction:"
    drafts: false
chat:
  auto_reply: true
