name: "devtopia"

services:
  mysql:
    image: mysql:8.0.36
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtopia
      MYSQL_USER: mysql
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - v_mysql_data:/var/lib/mysql

volumes:
  v_mysql_data:
