name: "devtopia"

services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtopia
      MYSQL_USER: mysql
      MYSQL_PASSWORD: p@ssw0rd
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf