name: "Pull Request Labeler"

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label manager for PRs and Issues based on configurable conditions
        uses: srvaroa/labeler@v1.10.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
